assets/sunshine.conf
sunshine/platform/linux.cpp

If we create a new PulseAudio recording stream without specifying a device name, PA will assume you want to record from the default source, which is usually a microphone. Fortunately, PA supports some magic device names (`@DEFAULT_SOURCE@`, `@DEFAULT_SINK@`, and `@DEFAULT_MONITOR@`) to indicate what we're looking for.
Using `@DEFAULT_MONITOR@` rather than `nullptr` prevents PA from picking an actual audio input source and should prevent users from having to manually specify the sink in most situations.

Use the default monitor rather than the default source

---

assets/sunshine.conf
sunshine/config.cpp

With multiple Sunshine hosts on the network, it's useful to have a way of distinguishing them by default. This behavior also mimics what GFE does.

Use hostname as the default Sunshine name

---

assets/sunshine.conf
sunshine/config.cpp
sunshine/config.h
sunshine/stream.cpp
sunshine/video.cpp
sunshine/video.h

GOP size should be infinite to avoid encoding periodic I-frames that reduce perceived quality due to hitting the bitrate ceiling. Clients will request I-frames when needed, so generating them periodically is unnecessary.
B-frames should be avoided because each B-frame increases decoder output latency by one frame. B-frames weren't actually used in the default configuration because H.264 Baseline doesn't support them. However, attempting to specify the H.264 High profile would cause the encoder to create them.
Additionally, I added support for the `x-nv-video[0].maxNumReferenceFrames` attribute to set the maximum number of reference frames. Some very conservative decoders will even delay output by `num_ref_frames`, so it's important to respect the client's request there.

Optimize encoding parameters for low-latency

---

assets/sunshine.conf
sunshine/config.cpp
sunshine/config.h
sunshine/nvhttp.cpp
sunshine/stream.cpp
sunshine/video.cpp
sunshine/video.h

This PR adds support for encoding in HEVC Main and HEVC Main10 profiles. On my test laptop, the performance of HEVC encoding is worse than H.264, so I left it disabled by default. This work required me to remove the `profile` configuration option, because HEVC and H.264 have different profiles and sometimes they are implied by the client's request (like Main10 for HDR mode). As part of the profile removal, I changed the default H.264 profile from Baseline to High to match what GFE uses.
I also added support for reading the `x-nv-video[0].encoderCscMode` which specifies the client's desired color space and color range. This fixes color conversion issues on some clients (Windows, Steam Link) which were not getting their requested color space and misinterpreting the video data as Rec 709 …

Add support for HEVC and client-specified colorspaces

---

assets/sunshine.conf
sunshine/config.cpp
sunshine/config.h
sunshine/video.cpp

Since most Moonlight clients request the fewest slices they can (usually 1, except on Android and PC with software decoding), our parallelism for H.264 encoding is limited to 1 thread in most cases regardless of what `threads` was set to. This can cause performance issues on systems where 1 CPU core is not enough to keep up with real-time encoding.
This new `min_threads` attribute replaces `threads` and provides a lower bound on the number of slices that will ensure we will have enough slices to be able to scale across enough threads to achieve good encoding performance.

Change threads option to min_threads

---

CMakeLists.txt
appveyor.yml

This PR adds a build artifact to the automated Windows builds in AppVeyor which archives a ZIP file which can be used to run Sunshine. This is currently archiving more MinGW DLLs than we need, but it's okay for now.
Example: https://ci.appveyor.com/project/cgutman/sunshine/builds/30248652/job/2kcat46lka747q22/artifacts

Archive Sunshine builds for Windows

---

sunshine/nvhttp.cpp
sunshine/platform/common.h
sunshine/platform/linux.cpp
sunshine/platform/windows.cpp

~~**Note: https://github.com/loki-47-6F-64/Simple-Web-Server/pull/1 needs to be merged and the submodule to be updated for this PR to build!**~~
This PR adds support for multi-homed hosts, so we will now properly report the local IP address corresponding to the actual connection we received. This also makes the reported local IP accurate even if our IP address changes while Sunshine is running.
I've also added support for retrieving the MAC address on Linux, so Wake-on-LAN works with Moonlight clients.

Support multi-homed hosts and plumb MAC addresses for Linux

---

CMakeLists.txt
sunshine/platform/windows.cpp

This PR adds support for Wake-on-LAN for Windows hosts by providing the MAC address in the serverinfo response.

Retrieve MAC address on Windows

---

sunshine/platform/linux_evdev.cpp
sunshine/platform/windows.cpp

This PR fixes extended keys not working on Windows (notably the arrow keys) and a couple keys being swapped on the number pad on Linux.

Fix incorrect key codes

---

sunshine/platform/common.h
sunshine/platform/linux.cpp
sunshine/platform/windows_dxgi.cpp
sunshine/video.cpp

This fixes the bug that Coolykoen reported on Discord where the display was garbled when the Windows host desktop was set to 1366x768. The cause was extra padding that broke the assumption that `row_pitch == 4 * width` (actual row pitch was 5504 instead of 5464). To fix this, I added pitch fields to `img_t` and use those values directly where applicable.

Fix row pitch being assumed to be 'width * 4'

---

sunshine/input.cpp
sunshine/input.h
sunshine/stream.cpp

In some cases, when client terminates the session using the CTRL+SHIFT+ALT+Q combination, the server does not handle the released modifiers correctly, and continues to keep them as "pressed". This PR should fix that

Fix Modifiers stuck on Host On Disconnection

---

sunshine/video.cpp

Parameter is needed to avoid infinite black screen with
"Waiting for IDR frame" in moonlight-qt (3.1.3) on Windows.
Tested on Windows 10 x64 host with moonlight-qt 3.1.3 Windows 10 x64 client.

Force IDR frames for libx265 encoder

---

assets/web/config.html

The amd_rc option is not set correctly on the Web UI. 
This patch should fix it

Fix Config Page AMD RC settings

---

assets/sunshine.conf
assets/web/config.html
sunshine/config.cpp
sunshine/rtsp.cpp
sunshine/stream.cpp
sunshine/stream.h

This PR increases the default FEC percentage to 20% to match GFE.
It also introduces support for the `x-nv-vqos[0].fec.minRequiredFecPackets`  attribute added in GFE 3.22. This enables clients to specify a minimum number of FEC shards per frame. If that minimum is not met, the FEC percentage is increased for that frame to meet the FEC shard minimum (even up to 200% for a single data shard frame). Like #112, Sunshine needs to start advertising a higher `appversion` for Moonlight to use this feature out of the box.
I also included parsing of some additional SDP attributes which will be required to support the encrypted control stream and encrypted audio which is required to advertise GFE 3.22 compliance.

Video FEC changes

---

sunshine/video.cpp

The current IDR frame logic sets `key_frame_nr` to a full second worth of frames in the future and actually causes 2 IDR frames to be sent for each request (once in the `idr_events->peek()` case and once `config.framerate` frames later when `frame_nr == key_frame_nr`). It also causes the `frame_nr` to potentially go backwards, leading to valid frames being discarded (which may be the original reason for the `key_frame_nr = end + config.framerate` hack).
All these bugs lead to spurious poor connection warnings in Moonlight (particularly apparent when first establishing a connection with Moonlight Qt) and poor responsiveness on lossy networks due to significant delays on IDR frames. Performance with modest packet loss (simulated using Clumsy network conditioner) is massively improved with …

Fix IDR frame delays after packet loss or client request

---

sunshine/platform/linux/input.cpp
sunshine/platform/windows/input.cpp

Since Moonlight can pass the Super key now with the "Capture system keyboard shortcuts" option, the old workaround of mapping right Alt to the Super key is no longer required. This allows the right Alt key to be used by applications/games.

Remove super key workaround

---

sunshine/nvhttp.cpp

This inconsistency doesn't cause any problems at the moment, but let's fix it anyway.

Update GfeVersion to be consistent with AppVersion

---

assets/sunshine.conf
assets/web/config.html
sunshine/config.cpp

During periods of poor connectivity, the ping timeout of 2 seconds
can easily be exceeded, especially with ENet's RTO backoff logic.
This causes an unnecessary disconnection when the connection would
have recovered on its own in a few seconds. Increasing the timeout
to 10 seconds should prevent spurious disconnections in most cases.
A 10 second timeout is also what GeForce Experience also uses.

Increase default ping timeout to 10 seconds

---

assets/web/config.html
sunshine/platform/common.h
sunshine/platform/linux/display.cpp
sunshine/stream.cpp
sunshine/video.cpp

We're not offloading scaling and YUV conversion from the CPU yet, so the gains aren't as high as one of the fully accelerated backends like Windows NVENC or Linux VAAPI.
Still, offloading the H.264/HEVC encoding itself is an improvement over doing everything on the CPU (especially for HEVC).
Partially fixes #45

Add basic NVENC support on Linux

---

sunshine/video.cpp

The internal assembly routines inside libswscale perform the RGB->YUV conversion using a fully planar output format, then have to perform an additional YUV420->NV12 conversion step.
NVENC can directly consume YUV420 input frames, so we can completely avoid this NV12 conversion and save quite a bit of CPU time in the process.
Using YUV420 directly allows us to completely get rid of the yuv2nv12 function which was at the top of the performance charts for cycles spent on the entire system while streaming.
NV12 (before):
YUV420 (after):

Reduce CPU usage with Linux NVENC

---

sunshine/crypto.cpp

Passing `X509_V_FLAG_PARTIAL_CHAIN` allows client certificates generated by Moonlight Embedded (and clients using the same cert generation code, like Moonlight Wii U, Moonlight Vita, etc.) to be accepted by Sunshine.
It appears the addition of the X509v3 SKID extension is confusing OpenSSL into thinking it's not a self-signed certification, which triggers the `X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE` error. I was never able to reproduce this myself (might be related to OpenSSL versions), but the [moonlight-wiiu](https://github.com/GaryOderNichts/moonlight-wiiu) developer did and confirmed this fixes it.
Fixes #132
Fixes #134

Fix X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE error with some embedded clients

---

appveyor.yml
sunshine/main.cpp
tools/CMakeLists.txt
tools/install-service.bat
tools/sunshinesvc.cpp
tools/uninstall-service.bat

This PR adds sunshinesvc.exe that can run as a Windows service and manages spawning sunshine.exe as LocalSystem in the active console session automatically (including restarting it if it crashes or is closed). There are several improvements that could be made (noted as TODOs in the code), but it works fairly well as is.
In addition to getting the benefit of automatically starting on boot, it also allows Moonlight clients to interact with the Winlogon UI and UAC dialogs since it's running as LocalSystem.
Right now it is installed via an `install-service.bat` file that will be in the root of the Sunshine-Windows.zip build artifact. Ultimately, I'd like to write a proper installer but that's for later.

Add Win32 service to run Sunshine as LocalSystem

---

sunshine/platform/linux/kmsgrab.cpp
sunshine/stream.cpp

With this patch (and vaapi + kmsgrab) CPU usage on my system dropped from 60% to 6% when streaming.
I guess the busy wait in capture is there because the sleep will end up sleeping for more than the specified duration?
On my system, on average, it would "oversleep" the next_frame time by:
```
busy wait = ~0.0005ms
1ns sleep = ~0.09ms
```
As this is way under 1ms, it should be more than enough for this use-case. Alternatively, it may be possible to improve it with changing the capture thread scheduling. 
As for the control broadcast thread, I think there is no reason at all to iterate that often?

Reduce CPU usage

---

gen-deb.in

The deb package does not install due to libcap not existing. The lib is called libcap2 now.

libcap-dev is associated to libcap2

---

sunshine/platform/linux/input.cpp

Currently there is a key on my QWERTZ-Layout that is not recognized at all by sunshine, responsible for <, | and >. 
This Key is basically an additional key to the normal QWERTY Layout, making it one key bigger than the US Keyboard. 
What follows is the way I extracted the information and applied it, just in case somebody wants to add something similar and has no idea where to start (as I had).
First, what is sent to sunshine by moonlight can be looked at here
https://github.com/moonlight-stream/moonlight-qt/blob/51b5f8046f1864e36cfa6efefbe2de71ef98ca92/app/streaming/input/keyboard.cpp#L211 
So one can actually compare what is sent to what is recognized when received. Sunshine manually goes through ALL keys line by line here https://github.com/moonlight-stream/moonlight-qt/blob/51b5f8046f1 …

Add non US Backslash for international keyboards on Linux

---

sunshine/input.cpp

As mentioned in #82, pressed keyboard input will not be converted into the given keymap. This is fixed with this commit.

Apply key rewrite also when keeping key pressed
